export const CreatorModuleData = [
    {
        id:"55454",
        image: "/assets/images/buyers-images/01.jpg",
        title: "Chicken Burger",
        email:"debbie.baker@example.com",
        walletid:"5",
        subslvl:"550",
        name: "Gustavo Rosser",
        type:" Processing",
        bidprice: "56",
        usdprice: "146326.32",
    
    },
    {
        id:"54564",
        image: "/assets/images/buyers-images/04.jpg",
        title: "Seafood Pizza",
        email:"jessica.hanson@example.com",
        walletid:"4",
        subslvl:"1000",
        name: "Marilyn Baptista",
        type:"Deleiverd",
        bidprice: "52",
        usdprice: "135874.44",
        
    },
    {
        id:"0124",
        image: "/assets/images/buyers-images/05.jpg",
        title: "Cheese Burger",
        email:"alma.lawson@example.com",
        walletid:"4",
        subslvl:"300",
        name: "Alena Bator",
        type:"Deleiverd",
        bidprice: "66",
        usdprice: "172456.02",
        
    },
    {
        id:"0105",
        image: "/assets/images/buyers-images/06.jpg",
        title: "Vegetarian Pizza",
        email:"georgia.young@example.com",
        walletid:"15",
        subslvl:"400",
        name: "Terry George",
        type:"   Processing",
        bidprice: "26",
        usdprice: "67937.22",
        
    },
    {
        id:"0114",
        image: "/assets/images/buyers-images/01.jpg",
        title: "Cheese Burger",
        email:"nathan.roberts@example.com",
        walletid:"20",
        subslvl:"800",
        name: "Ann Lipshutz",
        type:"Deleiverd",
        bidprice: "24",
        usdprice: "62711.28",
    },
    {
        id:"0116",
        image: "/assets/images/buyers-images/03.png",
        title: "Loaf Bread",
        email:"sara.cruz@example.com",
        walletid:"8",
        subslvl:"1500",
        name: "   Processing",
        type:"Processing",
        bidprice: "18",
        usdprice: "$ 47033.46",
        
    },
   
]