export const BuyersData = [
    {
        id:"55454",
        image: "/assets/images/buyers-images/01.jpg",
        title: "Chicken Burger",
        email:"Regular",
        walletid:"350",
        subslvl:"Lite",
        name: "Gustavo Rosser",
        type:"Timed Auction",
        bidprice: "56",
        usdprice: "146326.32",
    
    },
  
  
    {
        id:"0105",
        image: "/assets/images/buyers-images/04.jpg",
        title: "Seafood Pizza",
        email:"Medium",
        walletid:"800",
        subslvl:"Standard",
        name: "Terry George",
        type:"Fixed Price",
        bidprice: "26",
        usdprice: "67937.22",
        
    },
    {
        id:"0114",
        image: "/assets/images/buyers-images/05.jpg",
        title: "Cheese Burger",
        email:"Small",
        walletid:"200",
        subslvl:"Standard",
        name: "Ann Lipshutz",
        type:"Fixed Price",
        bidprice: "24",
        usdprice: "62711.28",
    },
    {
        id:"0116",
        image: "/assets/images/buyers-images/06.jpg",
        title: "Vegetarian Pizza",
        email:"Large",
        walletid:"600",
        subslvl:"Premium",
        name: "Davis Lipshutz",
        type:"Fixed Price",
        bidprice: "18",
        usdprice: "$ 47033.46",
        
    },
    {
        id:"0107",
        image: "/assets/images/buyers-images/01.jpg",
        title: "Cheese Burger",
        email:"Small",
        walletid:"600",
        subslvl:"QCwyz32q",
        name: "Carter Gouse",
        type:"Fixed Price",
        bidprice: "20",
        usdprice: "52259.40",
    },
    {
        id:"0109",
        image: "/assets/images/buyers-images/03.png",
        title: "Loaf Bread",
        email:"Regular",
        walletid:"300",
        subslvl:"Premium",
        name: "Carter Gouse",
        type:"Fixed Price",
        bidprice: "20",
        usdprice: "52259.40",
    }
]