import type { NextPage } from 'next'
import Head from 'next/head'
import { BuyersModule } from '../modules/buyersmodule/Buyersmodule'


const Buyersmodule = () => {
  return (
    <div className=''>
      <Head>
        <title>Food delivery | Products </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <BuyersModule/>    
    </div>
  )
}

export default Buyersmodule
