import type { NextPage } from 'next'
import Head from 'next/head'
import { CreatorrequestsModule } from '../modules/creatorrequestsmodule/creatorrequestsmodule'




const Creatorrequests = () => {
  return (
    <div className=''>
      <Head>
        <title>One Of A Mint Creator | Creatorrequests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CreatorrequestsModule/>    
    </div>
  )
}

export default Creatorrequests
