import type { NextPage } from 'next'
import Head from 'next/head'
import CreatorrequestsdetailsModule from '../modules/creatorrequestsdetails/CreatorrequestsdetailsModule'





const Creatorrequestsdetails = () => {
  return (
    <div className=''>
      <Head>
        <title>One Of A Mint Creator | Creatorrequestsdetails</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CreatorrequestsdetailsModule/>    
    </div>
  )
}

export default Creatorrequestsdetails
