
import Head from 'next/head'
import { CreatorModule } from '../modules/creatormodule/CreateModule'


const Creator = () => {
  return (
    <div className=''>
      <Head>
        <title>Food delivery | Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CreatorModule/>    
    </div>
  )
}

export default Creator
