import type { NextPage } from 'next'
import Head from 'next/head'
import { TransactionModule } from '../modules/transactionmodule/transactionmodule'


const Transaction = () => {
  return (
    <div className=''>
      <Head>
        <title>One Of A Mint Creator | Transaction-management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <TransactionModule/>    
    </div>
  )
}

export default Transaction
